### ISSUE TITLE
Publikacja w formie wtyczki w ramach wydać na GitHub

### ISSUE THREAD

**Issue by Triloworld** [PayU-EMEA/plugin_prestashop#319]
Na ten moment strona PayU przekierowuje na te repozytorium i osoby które chcą wgrać moduł pobierają pliki źródłowe.
<img width="532" alt="Zrzut ekranu 2023-08-8 o 11 59 29" src="https://github.com/PayU-EMEA/plugin_prestashop/assets/2671726/77eb57a7-d3e0-4ad5-885f-81df73154247">

Prawidłowy sposób to posiadanie paczki z kodem w formie modułu i prawidłowym formacie. Umożliwi to aktualizację z panelu wtyczki i jej instalację dla nowych użytkowników.

Propozycja to GitHub Action z tą częścią która generuje plik zip w prawidłowy sposób (jako `draft` ale można też `release` etc):
```yml
      - name: Archive Generate
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: 'payu'
          path: '${{ env.REPOSITORY_NAME }}/'
          filename: '${{ env.REPOSITORY_NAME }}.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'

      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: 'release-drafter.yml'
          tag: 'draft'
          upload_url: ${{ steps.archive_release.outputs.upload_url }}

      - name: Archive Release
        id: archive_release
        run: |
          gh release upload --clobber ${{ env.VERSION }} ${{ env.FILES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: 'draft'
          FILES: payu/${{ env.REPOSITORY_NAME }}.zip
```

Oczywiście - cache i composer wskazany by generował w tym procesie cały moduł i publikować jako wydanie
Nie oczekuje automatu do testów etc a jedynie dołączający plik zip
